package models;

public enum Jobs {
    ENCAMISAR_BLOQUE, ANILLOS_PARA_BASES, RIMADA_DE_BIELAS, AGRANDAR_BASES, RECTIFICAR_BLOQUE, CAMBIO_DE_GUIAS, CIRCULO_BIELAS, CEPILLADO_CULATAS, CIGUEÑAL, RIMAS_GUIAS, ENSAMBLAR_PISTONES, CAMISA_CIGUEÑAL, CULATAS, CAMBIO_BUJES_ARBOL_LEVAS, LAVADO, HACER_ARANDELA
}
